version: '3'

services:
  postgres:
    build: ./postgresd 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres/var/lib/postgresql/data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/