DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tweets;
DROP TABLE IF EXISTS replies;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS hashtags;
DROP TABLE IF EXISTS retweets;
DROP TABLE IF EXISTS followers;